### ISSUE TITLE
on debug keys hcaptcha doesn't work

### ISSUE THREAD

**Issue by beqramo** [hCaptcha/react-native-hcaptcha#79]
Hi,

I noticed recently, without updating the SDK, that sdk doesn't return the token when the sitekey is the dev key. 
It works well on prod...

I updated the SDK, but still facing the same issue.

please tell me if you guys need any more details.

**Comment by e271828-** [comment]
@beqramo which sitekey are you using? Nothing has changed here, to my knowledge.

1. Does it only happen with a particular SDK version?
2. Does it still happen if you try in the example app?

**Comment by beqramo** [comment]
I just noticed, demo site key got updated to this: 00000000-0000-0000-0000-000000000000 from this 10000000-ffff-ffff-ffff-000000000001

**Comment by beqramo** [comment]
@e271828-  I have updated the keys but still the same:

These are the logs:
```
[BrowserEngineKit] Failed to terminate process: Error Domain=com.apple.extensionKit.errorDomain Code=18 "(null)" UserInfo={NSUnderlyingError=0x600000e4be10 {Error
Domain=RBSRequestErrorDomain Code=3 "No such process found" UserInfo={NSLocalizedFailureReason=No such process found}}}
 LOG  error event <--- this is coming from the onMessage event
[BrowserEngineKit] Failed to terminate process: Error Domain=com.apple.extensionKit.errorDomain Code=18 "(null)" UserInfo={NSUnderlyingError=0x600000ee3f60 {Error
Domain=RBSRequestErrorDomain Code=3 "No such process found" UserInfo={NSLocalizedFailureReason=No such process found}}}
[BrowserEngineKit] Failed to terminate process: Error Domain=com.apple.extensionKit.errorDomain Code=18 "(null)" UserInfo={NSUnderlyingError=0x600000f00cf0 {Error
Domain=RBSRequestErrorDomain Code=3 "No such process found" UserInfo={NSLocalizedFailureReason=No such process found}}}
[RemoteTextInput] -[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:]  perform input operation requires a valid sessionID. inputModality = Keyboard,
inputOperation = <null selector>, customInfoType = UIEmojiSearchOperations

```

I'm on     
    "expo": "^52.0.42",  
    "react-native-webview": "13.13.5",

This thing started to happen after I updated the Expo version from 50.

**Comment by e271828-** [comment]
> [@e271828-](https://github.com/e271828-) hi, any update on this?
> 
> Thanks

This is on the backlog, so I'd suggest pinning to Expo 50 for the moment.

**Comment by CAMOBAP** [comment]
@beqramo could you please try the workaround described in https://github.com/react-native-modal/react-native-modal/issues/807 will it work for you?

**Comment by beqramo** [comment]
it did not work @CAMOBAP , I see the same issues that I mentioned above.

**Comment by e271828-** [comment]
> [@CAMOBAP](https://github.com/CAMOBAP) any update? I'm really stuck here from QA perspective...

We'll be taking a closer look this week, but why is this blocking you? Are you not able to pin to Expo 50?

**Comment by CAMOBAP** [comment]
Summary on the issue:
1. Tested with latest Expo 53 no issue spotted. Tried different types of the keys: demo and private
2. I have issues with downgrading Expor 53 example to 52 (swift compilation errors)

Action items:
1. In '2.0.0' we changed API to return a more clear error message instead "error" string. Could you please try 2.0.0 version of SDK
2. Provide a full log for iOS
3. Need information about Xcode verison, iOS version (emulator or hardware)

**Comment by beqramo** [comment]
Hi @CAMOBAP, I have updated to the latest version, and now it works well.
One thing that doesn't work is that on the dev key, it is showing me a puzzle to solve all the time.

On both: 00000000-0000-0000-0000-000000000000  and 10000000-ffff-ffff-ffff-000000000001
Is that expected?
Additionally, after sending it to BE, BE states that it can't validate the CAPTCHA token.
Can you help here?

Thanks
